//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.14 at 06:00:21 PM MESZ 
//


package de.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Quizgame.Highscore }
     * 
     */
    public Quizgame.Highscore createQuizgameHighscore() {
        return new Quizgame.Highscore();
    }

    /**
     * Create an instance of {@link Quizgame.Quizfrage.Antwort }
     * 
     */
    public Quizgame.Quizfrage.Antwort createQuizgameQuizfrageAntwort() {
        return new Quizgame.Quizfrage.Antwort();
    }

    /**
     * Create an instance of {@link Quizgame.Quizfrage.Bild }
     * 
     */
    public Quizgame.Quizfrage.Bild createQuizgameQuizfrageBild() {
        return new Quizgame.Quizfrage.Bild();
    }

    /**
     * Create an instance of {@link Quizgame.Quizfrage }
     * 
     */
    public Quizgame.Quizfrage createQuizgameQuizfrage() {
        return new Quizgame.Quizfrage();
    }

    /**
     * Create an instance of {@link Quizgame }
     * 
     */
    public Quizgame createQuizgame() {
        return new Quizgame();
    }

}
